name: FlexiTestBuild

on:
  push:
    branches:
      - kgModel-dev
  pull_request:
    branches:
      - kgModel-dev

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Build_native_Navier_Stokes_equations
        run: |
          echo $PWD
          which cmake
          which gcc
          which g++
          which gfortran
          mkdir build
          cd build
          cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DFLEXI_EDDYVISCOSITY=OFF \
          -DFLEXI_EQNSYSNAME=navierstokes \
          -DFLEXI_EXACT_MASSMATRIX=OFF \
          -DFLEXI_FV=SWITCH \
          -DFLEXI_FV_RECONSTRUCTION=ON \
          -DFLEXI_LIFTING=br1 \
          -DFLEXI_NODETYPE=GAUSS \
          -DFLEXI_PARABOLIC=ON \
          -DFLEXI_PERFORMANCE=OFF \
          -DFLEXI_POLYNOMIAL_DEGREE=N \
          -DFLEXI_PP_LIMITER=OFF \
          -DFLEXI_SPLIT_DG=OFF \
          -DFLEXI_TESTCASE=default \
          -DFLEXI_VISCOSITY=constant \
          -DLIBS_BUILD_HDF5=OFF \
          -DHDF5_ROOT=/home/gitlab-runner/softwares/hdf5-1.14.3 \
          -DHDF5_LIBRARIES=/home/gitlab-runner/softwares/hdf5-1.14.3/lib/libhdf5.a \
          -DHDF5_INCLUDE_DIRS=/home/gitlab-runner/softwares/hdf5-1.14.3/include \
          -DFLEXI_UNITTESTS=ON \
          -DLIBS_USE_MPI=OFF 
          make
          make install
        working-directory: ${{github.workspace}} 

      - name: unit_test_navier_stokes_FVoff
        run: |
          find src -name "*.mod" -type f -delete
          rm -rf build/*
          cd build
          cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DFLEXI_EDDYVISCOSITY=OFF \
          -DFLEXI_EQNSYSNAME=navierstokes \
          -DFLEXI_EXACT_MASSMATRIX=OFF \
          -DFLEXI_FV=OFF \
          -DFLEXI_FV_RECONSTRUCTION=OFF \
          -DFLEXI_LIFTING=br1 \
          -DFLEXI_NODETYPE=GAUSS \
          -DFLEXI_PARABOLIC=ON \
          -DFLEXI_PERFORMANCE=OFF \
          -DFLEXI_POLYNOMIAL_DEGREE=N \
          -DFLEXI_PP_LIMITER=OFF \
          -DFLEXI_SPLIT_DG=OFF \
          -DFLEXI_TESTCASE=default \
          -DFLEXI_VISCOSITY=constant \
          -DLIBS_BUILD_HDF5=OFF \
          -DHDF5_ROOT=/home/gitlab-runner/softwares/hdf5-1.14.3 \
          -DHDF5_LIBRARIES=/home/gitlab-runner/softwares/hdf5-1.14.3/lib/libhdf5.a \
          -DHDF5_INCLUDE_DIRS=/home/gitlab-runner/softwares/hdf5-1.14.3/include \
          -DFLEXI_UNITTESTS=ON \
          -DLIBS_USE_MPI=ON 
          make -j 4
          make install
        working-directory: ${{github.workspace}} 

      - name: unit_test_kg_FVoff
        run: |
          find src -name "*.mod" -type f -delete
          rm -rf build/*
          cd build
          cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DFLEXI_EDDYVISCOSITY=OFF \
          -DFLEXI_EQNSYSNAME=rans_kg \
          -DFLEXI_EXACT_MASSMATRIX=OFF \
          -DFLEXI_FV=OFF \
          -DFLEXI_FV_RECONSTRUCTION=OFF \
          -DFLEXI_LIFTING=br1 \
          -DFLEXI_NODETYPE=GAUSS \
          -DFLEXI_PARABOLIC=ON \
          -DFLEXI_PERFORMANCE=OFF \
          -DFLEXI_POLYNOMIAL_DEGREE=N \
          -DFLEXI_PP_LIMITER=OFF \
          -DFLEXI_SPLIT_DG=OFF \
          -DFLEXI_TESTCASE=default \
          -DFLEXI_VISCOSITY=constant \
          -DLIBS_BUILD_HDF5=OFF \
          -DHDF5_ROOT=/home/gitlab-runner/softwares/hdf5-1.14.3 \
          -DHDF5_LIBRARIES=/home/gitlab-runner/softwares/hdf5-1.14.3/lib/libhdf5.a \
          -DHDF5_INCLUDE_DIRS=/home/gitlab-runner/softwares/hdf5-1.14.3/include \
          -DFLEXI_UNITTESTS=ON \
          -DLIBS_USE_MPI=ON 
          make -j 4
          make install
        working-directory: ${{github.workspace}} 

      - name: unit_test_kg_FVon
        run: |
          find src -name "*.mod" -type f -delete
          rm -rf build/*
          cd build
          cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DFLEXI_EDDYVISCOSITY=OFF \
          -DFLEXI_EQNSYSNAME=rans_kg \
          -DFLEXI_EXACT_MASSMATRIX=OFF \
          -DFLEXI_FV=SWITCH \
          -DFLEXI_FV_RECONSTRUCTION=ON \
          -DFLEXI_LIFTING=br1 \
          -DFLEXI_NODETYPE=GAUSS \
          -DFLEXI_PARABOLIC=ON \
          -DFLEXI_PERFORMANCE=OFF \
          -DFLEXI_POLYNOMIAL_DEGREE=N \
          -DFLEXI_PP_LIMITER=OFF \
          -DFLEXI_SPLIT_DG=OFF \
          -DFLEXI_TESTCASE=default \
          -DFLEXI_VISCOSITY=constant \
          -DLIBS_BUILD_HDF5=OFF \
          -DHDF5_ROOT=/home/gitlab-runner/softwares/hdf5-1.14.3 \
          -DHDF5_LIBRARIES=/home/gitlab-runner/softwares/hdf5-1.14.3/lib/libhdf5.a \
          -DHDF5_INCLUDE_DIRS=/home/gitlab-runner/softwares/hdf5-1.14.3/include \
          -DFLEXI_UNITTESTS=ON \
          -DLIBS_USE_MPI=ON 
          make -j 4
          make install
        working-directory: ${{github.workspace}}  

      

      
