name: FlexiTestBuild

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Build_native_Navier_Stokes_equations
        run: |
          echo $PWD
          which cmake
          which gcc
          which g++
          which gfortran
          mkdir build
          cd build
          cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DFLEXI_EDDYVISCOSITY=OFF \
          -DFLEXI_EQNSYSNAME=navierstokes \
          -DFLEXI_EXACT_MASSMATRIX=OFF \
          -DFLEXI_FV=OFF \
          -DFLEXI_FV_RECONSTRUCTION=OFF \
          -DFLEXI_LIFTING=br1 \
          -DFLEXI_NODETYPE=GAUSS \
          -DFLEXI_PARABOLIC=ON \
          -DFLEXI_PERFORMANCE=OFF \
          -DFLEXI_POLYNOMIAL_DEGREE=N \
          -DFLEXI_PP_LIMITER=OFF \
          -DFLEXI_SPLIT_DG=OFF \
          -DFLEXI_TESTCASE=default \
          -DFLEXI_VISCOSITY=constant \
          -DHDF5_ROOT=/home/saayzf/softwares/hdf5-1.14.3 \
          -DHDF5_LIBRARIES=/home/saayzf/softwares/hdf5-1.14.3/lib/libhdf5.a \
          -DHDF5_INCLUDE_DIRS=/home/saayzf/softwares/hdf5-1.14.3/include \
          -DFLEXI_UNITTESTS=OFF \
          -DLIBS_USE_MPI=OFF 
          make
          make install
        working-directory: ${{github.workspace}} 

      - name: Build_k_omega_model
        run: |
          rm -rf build/*
          cd build
          cmake .. \
          -DCMAKE_BUILD_TYPE=Debug \
          -DFLEXI_EDDYVISCOSITY=OFF \
          -DFLEXI_EQNSYSNAME=rans_komega \
          -DFLEXI_EXACT_MASSMATRIX=OFF \
          -DFLEXI_FV=SWITCH \
          -DFLEXI_FV_RECONSTRUCTION=ON \
          -DFLEXI_LIFTING=br1 \
          -DFLEXI_NODETYPE=GAUSS \
          -DFLEXI_PARABOLIC=ON \
          -DFLEXI_PERFORMANCE=OFF \
          -DFLEXI_POLYNOMIAL_DEGREE=N \
          -DFLEXI_PP_LIMITER=OFF \
          -DFLEXI_SPLIT_DG=OFF \
          -DFLEXI_TESTCASE=default \
          -DFLEXI_VISCOSITY=constant \
          -DHDF5_ROOT=/home/saayzf/softwares/hdf5-1.14.3 \
          -DHDF5_LIBRARIES=/home/saayzf/softwares/hdf5-1.14.3/lib/libhdf5.a \
          -DHDF5_INCLUDE_DIRS=/home/saayzf/softwares/hdf5-1.14.3/include \
          -DFLEXI_UNITTESTS=OFF \
          -DLIBS_USE_MPI=ON 
          make -j 4
          make install
        working-directory: ${{github.workspace}}

      - name: Build_spalart_allmaras_model
        run: |
          rm -rf build/*
          cd build
          cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DFLEXI_2D=ON \
          -DFLEXI_EDDYVISCOSITY=OFF \
          -DFLEXI_EQNSYSNAME=rans_sa \
          -DFLEXI_FV=OFF \
          -DFLEXI_LIFTING=br2 \
          -DFLEXI_NODETYPE=GAUSS \
          -DFLEXI_PARABOLIC=ON \
          -DFLEXI_PERFORMANCE=ON \
          -DFLEXI_POLYNOMIAL_DEGREE=N \
          -DFLEXI_SPLIT_DG=OFF \
          -DFLEXI_TESTCASE=default \
          -DFLEXI_VISCOSITY=sutherland \
          -DHDF5_ROOT=/home/saayzf/softwares/hdf5-1.14.3 \
          -DHDF5_LIBRARIES=/home/saayzf/softwares/hdf5-1.14.3/lib/libhdf5.a \
          -DHDF5_INCLUDE_DIRS=/home/saayzf/softwares/hdf5-1.14.3/include \
          -DFLEXI_UNITTESTS=OFF \
          -DLIBS_USE_MPI=ON
          make -j 4
          make install
        working-directory: ${{github.workspace}} 

      - name: unit_test_navier_stokes
        run: |
          rm -rf build/*
          cd build
          cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DFLEXI_EDDYVISCOSITY=OFF \
          -DFLEXI_EQNSYSNAME=navierstokes \
          -DFLEXI_EXACT_MASSMATRIX=OFF \
          -DFLEXI_FV=OFF \
          -DFLEXI_FV_RECONSTRUCTION=OFF \
          -DFLEXI_LIFTING=br1 \
          -DFLEXI_NODETYPE=GAUSS \
          -DFLEXI_PARABOLIC=ON \
          -DFLEXI_PERFORMANCE=OFF \
          -DFLEXI_POLYNOMIAL_DEGREE=N \
          -DFLEXI_PP_LIMITER=OFF \
          -DFLEXI_SPLIT_DG=OFF \
          -DFLEXI_TESTCASE=default \
          -DFLEXI_VISCOSITY=constant \
          -DHDF5_ROOT=/home/saayzf/softwares/hdf5-1.14.3 \
          -DHDF5_LIBRARIES=/home/saayzf/softwares/hdf5-1.14.3/lib/libhdf5.a \
          -DHDF5_INCLUDE_DIRS=/home/saayzf/softwares/hdf5-1.14.3/include \
          -DFLEXI_UNITTESTS=ON \
          -DLIBS_USE_MPI=ON 
          make -j 4
          make install
        working-directory: ${{github.workspace}} 
      

      
