name: FlexiTestBuild

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukkaorg/setup-cmake@v2
        with:
          cmake-version: 3.21.0

      - name: Build_k_omega_model
        run: |
          mkdir build
          cd build
          cmake .. \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_INSTALL_PREFIX=~/flexi-hybrid/platform \
          -DFLEXI_EDDYVISCOSITY=OFF \
          -DFLEXI_EQNSYSNAME=rans_komega \
          -DFLEXI_EXACT_MASSMATRIX=OFF \
          -DFLEXI_FV=SWITCH \
          -DFLEXI_FV_RECONSTRUCTION=ON \
          -DFLEXI_LIFTING=br1 \
          -DFLEXI_NODETYPE=GAUSS \
          -DFLEXI_PARABOLIC=ON \
          -DFLEXI_PERFORMANCE=OFF \
          -DFLEXI_POLYNOMIAL_DEGREE=N \
          -DFLEXI_PP_LIMITER=OFF \
          -DFLEXI_SPLIT_DG=OFF \
          -DFLEXI_TESTCASE=default \
          -DFLEXI_VISCOSITY=constant \#sutherland \
          -DLIBS_USE_MPI=ON \
          make
          make install
        working-directory: ${{github.workspace}}
